apiVersion: v1
kind: Secret
metadata:
  name: fte-secrets
  namespace: customer-success-fte
type: Opaque
stringData:
  GEMINI_API_KEY: GEMINI_API_KEY
  DATABASE_URL: DATABASE_URL
  GMAIL_CREDENTIALS_JSON: GMAIL_CREDENTIALS_JSON
  GMAIL_PUBSUB_TOPIC: GMAIL_PUBSUB_TOPIC
  WHATSAPP_OWN_NUMBER: WHATSAPP_OWN_NUMBER
